//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyDemoApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int id { get; set; }
        public string name { get; set; }
        public int catid { get; set; }
        public string imageurl { get; set; }
        public string price { get; set; }
        public bool isactive { get; set; }
        public string description { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
